In [14]:
for i in range(1,50):
    print(f"........................")
    print(f"multipication of {i}.")
    print(f"")
    for j in range(1,11):
        print(f"{i}*{j}= {i*j}")

........................
multipication of 1.

1*1= 1
1*2= 2
1*3= 3
1*4= 4
1*5= 5
1*6= 6
1*7= 7
1*8= 8
1*9= 9
1*10= 10
........................
multipication of 2.

2*1= 2
2*2= 4
2*3= 6
2*4= 8
2*5= 10
2*6= 12
2*7= 14
2*8= 16
2*9= 18
2*10= 20
........................
multipication of 3.

3*1= 3
3*2= 6
3*3= 9
3*4= 12
3*5= 15
3*6= 18
3*7= 21
3*8= 24
3*9= 27
3*10= 30
........................
multipication of 4.

4*1= 4
4*2= 8
4*3= 12
4*4= 16
4*5= 20
4*6= 24
4*7= 28
4*8= 32
4*9= 36
4*10= 40
........................
multipication of 5.

5*1= 5
5*2= 10
5*3= 15
5*4= 20
5*5= 25
5*6= 30
5*7= 35
5*8= 40
5*9= 45
5*10= 50
........................
multipication of 6.

6*1= 6
6*2= 12
6*3= 18
6*4= 24
6*5= 30
6*6= 36
6*7= 42
6*8= 48
6*9= 54
6*10= 60
........................
multipication of 7.

7*1= 7
7*2= 14
7*3= 21
7*4= 28
7*5= 35
7*6= 42
7*7= 49
7*8= 56
7*9= 63
7*10= 70
........................
multipication of 8.

8*1= 8
8*2= 16
8*3= 24
8*4= 32
8*5= 40
8*6= 48
8*7= 56
8*8= 64
8*9= 72
8*10= 80
........................
multipication of 9.

9*1= 9
9*2= 18
9*3= 27
9*4= 36
9*5= 45
9*6= 54
9*7= 63
9*8= 72
9*9= 81
9*10= 90
........................
multipication of 10.

10*1= 10
10*2= 20
10*3= 30
10*4= 40
10*5= 50
10*6= 60
10*7= 70
10*8= 80
10*9= 90
10*10= 100
........................
multipication of 11.

11*1= 11
11*2= 22
11*3= 33
11*4= 44
11*5= 55
11*6= 66
11*7= 77
11*8= 88
11*9= 99
11*10= 110
........................
multipication of 12.

12*1= 12
12*2= 24
12*3= 36
12*4= 48
12*5= 60
12*6= 72
12*7= 84
12*8= 96
12*9= 108
12*10= 120
........................
multipication of 13.

13*1= 13
13*2= 26
13*3= 39
13*4= 52
13*5= 65
13*6= 78
13*7= 91
13*8= 104
13*9= 117
13*10= 130
........................
multipication of 14.

14*1= 14
14*2= 28
14*3= 42
14*4= 56
14*5= 70
14*6= 84
14*7= 98
14*8= 112
14*9= 126
14*10= 140
........................
multipication of 15.

15*1= 15
15*2= 30
15*3= 45
15*4= 60
15*5= 75
15*6= 90
15*7= 105
15*8= 120
15*9= 135
15*10= 150
........................
multipication of 16.

16*1= 16
16*2= 32
16*3= 48
16*4= 64
16*5= 80
16*6= 96
16*7= 112
16*8= 128
16*9= 144
16*10= 160
........................
multipication of 17.

17*1= 17
17*2= 34
17*3= 51
17*4= 68
17*5= 85
17*6= 102
17*7= 119
17*8= 136
17*9= 153
17*10= 170
........................
multipication of 18.

18*1= 18
18*2= 36
18*3= 54
18*4= 72
18*5= 90
18*6= 108
18*7= 126
18*8= 144
18*9= 162
18*10= 180
........................
multipication of 19.

19*1= 19
19*2= 38
19*3= 57
19*4= 76
19*5= 95
19*6= 114
19*7= 133
19*8= 152
19*9= 171
19*10= 190
........................
multipication of 20.

20*1= 20
20*2= 40
20*3= 60
20*4= 80
20*5= 100
20*6= 120
20*7= 140
20*8= 160
20*9= 180
20*10= 200
........................
multipication of 21.

21*1= 21
21*2= 42
21*3= 63
21*4= 84
21*5= 105
21*6= 126
21*7= 147
21*8= 168
21*9= 189
21*10= 210
........................
multipication of 22.

22*1= 22
22*2= 44
22*3= 66
22*4= 88
22*5= 110
22*6= 132
22*7= 154
22*8= 176
22*9= 198
22*10= 220
........................
multipication of 23.

23*1= 23
23*2= 46
23*3= 69
23*4= 92
23*5= 115
23*6= 138
23*7= 161
23*8= 184
23*9= 207
23*10= 230
........................
multipication of 24.

24*1= 24
24*2= 48
24*3= 72
24*4= 96
24*5= 120
24*6= 144
24*7= 168
24*8= 192
24*9= 216
24*10= 240
........................
multipication of 25.

25*1= 25
25*2= 50
25*3= 75
25*4= 100
25*5= 125
25*6= 150
25*7= 175
25*8= 200
25*9= 225
25*10= 250
........................
multipication of 26.

26*1= 26
26*2= 52
26*3= 78
26*4= 104
26*5= 130
26*6= 156
26*7= 182
26*8= 208
26*9= 234
26*10= 260
........................
multipication of 27.

27*1= 27
27*2= 54
27*3= 81
27*4= 108
27*5= 135
27*6= 162
27*7= 189
27*8= 216
27*9= 243
27*10= 270
........................
multipication of 28.

28*1= 28
28*2= 56
28*3= 84
28*4= 112
28*5= 140
28*6= 168
28*7= 196
28*8= 224
28*9= 252
28*10= 280
........................
multipication of 29.

29*1= 29
29*2= 58
29*3= 87
29*4= 116
29*5= 145
29*6= 174
29*7= 203
29*8= 232
29*9= 261
29*10= 290
........................
multipication of 30.

30*1= 30
30*2= 60
30*3= 90
30*4= 120
30*5= 150
30*6= 180
30*7= 210
30*8= 240
30*9= 270
30*10= 300
........................
multipication of 31.

31*1= 31
31*2= 62
31*3= 93
31*4= 124
31*5= 155
31*6= 186
31*7= 217
31*8= 248
31*9= 279
31*10= 310
........................
multipication of 32.

32*1= 32
32*2= 64
32*3= 96
32*4= 128
32*5= 160
32*6= 192
32*7= 224
32*8= 256
32*9= 288
32*10= 320
........................
multipication of 33.

33*1= 33
33*2= 66
33*3= 99
33*4= 132
33*5= 165
33*6= 198
33*7= 231
33*8= 264
33*9= 297
33*10= 330
........................
multipication of 34.

34*1= 34
34*2= 68
34*3= 102
34*4= 136
34*5= 170
34*6= 204
34*7= 238
34*8= 272
34*9= 306
34*10= 340
........................
multipication of 35.

35*1= 35
35*2= 70
35*3= 105
35*4= 140
35*5= 175
35*6= 210
35*7= 245
35*8= 280
35*9= 315
35*10= 350
........................
multipication of 36.

36*1= 36
36*2= 72
36*3= 108
36*4= 144
36*5= 180
36*6= 216
36*7= 252
36*8= 288
36*9= 324
36*10= 360
........................
multipication of 37.

37*1= 37
37*2= 74
37*3= 111
37*4= 148
37*5= 185
37*6= 222
37*7= 259
37*8= 296
37*9= 333
37*10= 370
........................
multipication of 38.

38*1= 38
38*2= 76
38*3= 114
38*4= 152
38*5= 190
38*6= 228
38*7= 266
38*8= 304
38*9= 342
38*10= 380
........................
multipication of 39.

39*1= 39
39*2= 78
39*3= 117
39*4= 156
39*5= 195
39*6= 234
39*7= 273
39*8= 312
39*9= 351
39*10= 390
........................
multipication of 40.

40*1= 40
40*2= 80
40*3= 120
40*4= 160
40*5= 200
40*6= 240
40*7= 280
40*8= 320
40*9= 360
40*10= 400
........................
multipication of 41.

41*1= 41
41*2= 82
41*3= 123
41*4= 164
41*5= 205
41*6= 246
41*7= 287
41*8= 328
41*9= 369
41*10= 410
........................
multipication of 42.

42*1= 42
42*2= 84
42*3= 126
42*4= 168
42*5= 210
42*6= 252
42*7= 294
42*8= 336
42*9= 378
42*10= 420
........................
multipication of 43.

43*1= 43
43*2= 86
43*3= 129
43*4= 172
43*5= 215
43*6= 258
43*7= 301
43*8= 344
43*9= 387
43*10= 430
........................
multipication of 44.

44*1= 44
44*2= 88
44*3= 132
44*4= 176
44*5= 220
44*6= 264
44*7= 308
44*8= 352
44*9= 396
44*10= 440
........................
multipication of 45.

45*1= 45
45*2= 90
45*3= 135
45*4= 180
45*5= 225
45*6= 270
45*7= 315
45*8= 360
45*9= 405
45*10= 450
........................
multipication of 46.

46*1= 46
46*2= 92
46*3= 138
46*4= 184
46*5= 230
46*6= 276
46*7= 322
46*8= 368
46*9= 414
46*10= 460
........................
multipication of 47.

47*1= 47
47*2= 94
47*3= 141
47*4= 188
47*5= 235
47*6= 282
47*7= 329
47*8= 376
47*9= 423
47*10= 470
........................
multipication of 48.

48*1= 48
48*2= 96
48*3= 144
48*4= 192
48*5= 240
48*6= 288
48*7= 336
48*8= 384
48*9= 432
48*10= 480
........................
multipication of 49.

49*1= 49
49*2= 98
49*3= 147
49*4= 196
49*5= 245
49*6= 294
49*7= 343
49*8= 392
49*9= 441
49*10= 490

In [17]:
a= (1,2,3)

In [18]:
help(a)

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |
 |  Built-in immutable sequence.
 |
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |
 |  If the argument is a tuple, the return value is the same object.
 |
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return key in self.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  count(self, value, /)
 |      Return number of occurrences of value.
 |
 |  index(self, value, start=0, stop=9223372036854775807, /)
 |      Return first index of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.

In [27]:
sum = 0
for i in range(1,101):
    sum += i

In [28]:
sum

5050

In [37]:
rows = 6
for i in range(rows):
    for j in range(i):
        print(f"*", end='')
    print("")

*
**
***
****
*****